## @section Global Parameters
autoscaling: 
  enabled: false 

image:
  repository: lightdash/lightdash
  pullPolicy: IfNotPresent
  tag: ""


postgresql:
  enabled: true
  ## with Postgres 10 helm chart, user "postgres" has superuser privileges (fixing lightdash uuid)
  auth:
    username: lightdash
    password: ""
    database: lightdash
    existingSecret: ""
    secretKeys:
      userPasswordKey: "password"
  commonAnnotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    
externalDatabase:
  host: localhost
  user: lightdash
  password: ""
  existingSecret: ""
  secretKeys:
    passwordKey: "postgresql-password"
  database: lightdash
  port: 5432

scheduler:
  replicas: 1
  resources:
    requests:
      memory: 725Mi
      cpu: 475m
      ephemeral-storage: 1Gi
  sqlProxy:
    resources:
      requests:
        memory: 25Mi
        cpu: 25m
        ephemeral-storage: 10Mi
 