{{- if not .Values.postgresql.enabled -}}
{{- if not .Values.externalDatabase.existingSecret -}}
# The user is using an external database and has not provided a secret with the credentials.
# This creates a secret with the password provided in the values.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lightdash.database.secretName" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
data:
  {{ include "lightdash.database.secret.passwordKey" . }}: {{ (include "lightdash.database.password" .) | b64enc}}
{{- end }}
{{- end }}
