{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lightdash.fullname" . }}-migration-secrets
  annotations:
    helm.sh/hook: {{ if not .Values.postgresql.enabled }}pre-install,{{ end }}pre-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    {{- include "lightdash.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ default "MISSING" $value | b64enc | quote }}
{{- end }}
{{- end }}
