apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "lightdash.fullname" . }}-migrations
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lightdash.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["echo", "'Migrations completed'"]
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ (include "lightdash.database.secretName" .) }}
                  key: {{ (include "lightdash.database.secret.passwordKey" .) }}
            {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "lightdash.fullname" $ }}
            {{ if .Values.secrets }}
            - secretRef:
                name: {{ template "lightdash.fullname" $ }}
            {{ end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}