{{- $createNatsAuthSecret := eq (include "lightdash.nats.auth.createSecret" .) "true" -}}
{{- if or .Values.secrets $createNatsAuthSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lightdash.fullname" . }}
  labels:
    {{- include "lightdash.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ default "MISSING" $value | b64enc | quote }}
{{- end }}
{{- if and $createNatsAuthSecret .Values.natsJetstream.connection.user }}
  {{ include "lightdash.nats.auth.userKey" . }}: {{ .Values.natsJetstream.connection.user | b64enc | quote }}
{{- end }}
{{- if and $createNatsAuthSecret .Values.natsJetstream.connection.password }}
  {{ include "lightdash.nats.auth.passwordKey" . }}: {{ .Values.natsJetstream.connection.password | b64enc | quote }}
{{- end }}
{{- if and $createNatsAuthSecret .Values.natsJetstream.connection.token }}
  {{ include "lightdash.nats.auth.tokenKey" . }}: {{ .Values.natsJetstream.connection.token | b64enc | quote }}
{{- end -}}
{{- end -}}
